services:
  - type: web
    runtime: static
    name: smartlearninglab-react
    buildCommand: npm ci && npx expo export --platform web
    staticPublishPath: dist
    envVars:
      - key: EXPO_PUBLIC_API_BASE_URL
        value: "https://smartlearninglab.onrender.com/api/v1"
      - key: EXPO_PUBLIC_API_URL
        value: "https://smartlearninglab.onrender.com/api/v1"
