import React,{useEffect,useRef,useState} from 'react';
import {Alert,KeyboardAvoidingView,Platform,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {AppShell,Button,Card,Header,Loading} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';
export default function AIChatScreen(){
 const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false);
 const inputRef=useRef(null); const scrollRef=useRef(null);
 useEffect(()=>{(async()=>{try{let cs=api.listOf(await api.conversations());let c=cs[0];if(!c)c=await api.createConversation({title:'Study Assistant'});setConversation(c);setMessages(api.listOf(await api.messages(api.idOf(c))));setTimeout(()=>inputRef.current?.focus?.(),120)}catch(e){Alert.alert('AI',e.message)}})()},[]);
 useEffect(()=>{setTimeout(()=>scrollRef.current?.scrollToEnd?.({animated:true}),60)},[messages]);
 const goLatest=()=>scrollRef.current?.scrollToEnd?.({animated:true});
 const send=async()=>{if(!text.trim()||!conversation)return;const msg=text.trim();setText('');setMessages(m=>[...m,{role:'user',message:msg,_id:`local-${Date.now()}`}]);setBusy(true);try{const saved=await api.saveMessage({conversation_id:api.idOf(conversation),conversationId:api.idOf(conversation),message:msg,language:'en',contextType:'general'});const tutor=await api.ragTutor({question:msg});const reply=await api.saveMessage({conversation_id:api.idOf(conversation),conversationId:api.idOf(conversation),message:tutor.answer,role:'assistant',sources:tutor.sources||[]});setMessages(m=>[...m.slice(0,-1),saved,{...reply,sources:tutor.sources||[]}])}catch(e){Alert.alert('Could not save message',e.message)}finally{setBusy(false)}};
 if(!conversation)return <AppShell><Header title="AI Study Tutor" subtitle="Your saved study conversation"/><Loading/></AppShell>;
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><AppShell><Header title="AI Study Tutor" subtitle="Ask questions and keep your conversation history."/><View style={{position:'relative'}}><Card style={{minHeight:380,maxHeight:560}}><ScrollView ref={scrollRef} showsVerticalScrollIndicator contentContainerStyle={{paddingBottom:8}}>{messages.length===0?<Text style={{color:colors.muted}}>Start with a question like “Explain present simple with examples.”</Text>:messages.map((m,i)=><View key={api.idOf(m)||i} style={{alignSelf:m.role==='user'?'flex-end':'flex-start',maxWidth:'88%',backgroundColor:m.role==='user'?colors.primary:'#F1F5F9',padding:12,borderRadius:15,marginBottom:9}}><Text style={{color:m.role==='user'?'#fff':colors.text,lineHeight:20}}>{m.message||m.content}</Text>{m.role!=='user'&&m.sources?.length>0&&<Text style={{color:colors.muted,fontSize:11,marginTop:7}}>Sources: {m.sources.map(x=>x.title).join(', ')}</Text>}</View>)}</ScrollView></Card><Pressable onPress={goLatest} accessibilityRole="button" style={({pressed})=>({position:'absolute',right:16,top:10,width:40,height:40,borderRadius:20,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',opacity:pressed?.75:1,elevation:5,zIndex:20,shadowOpacity:.15,shadowRadius:6})}><Text style={{color:'#fff',fontSize:20,fontWeight:'900'}}>↓</Text></Pressable></View><View style={{flexDirection:'row',gap:8,alignItems:'flex-end'}}><TextInput ref={inputRef} autoFocus value={text} onChangeText={setText} placeholder="Ask a study question..." placeholderTextColor={colors.subtle} multiline style={{flex:1,minHeight:50,maxHeight:110,borderWidth:1,borderColor:colors.border,borderRadius:13,padding:13,backgroundColor:'#fff',color:colors.text}}/><Button title={busy?'...':'Send'} onPress={send} disabled={busy||!text.trim()}/></View></AppShell></KeyboardAvoidingView>;
}
