import React,{useEffect,useState} from 'react';
import {Alert,Pressable,Text,View} from 'react-native';
import {AppShell,Badge,Button,Card,Field,Header,ProgressBar,Select} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';

const Tile=({icon,title,text,onPress,tone='blue'})=><Pressable onPress={onPress} style={({pressed})=>({flex:1,minWidth:230,opacity:pressed?.82:1})}><Card style={{height:'100%',borderColor:tone==='purple'?colors.purple:'#E2E8F0'}}><View style={{width:46,height:46,borderRadius:14,backgroundColor:tone==='purple'?colors.purpleSoft:colors.blueSoft,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:23}}>{icon}</Text></View><Text style={{fontSize:17,fontWeight:'900',color:colors.navy,marginTop:10}}>{title}</Text><Text style={{fontSize:12,color:colors.muted,lineHeight:18,marginTop:5}}>{text}</Text><Text style={{fontSize:12,color:colors.primary,fontWeight:'900',marginTop:10}}>Open →</Text></Card></Pressable>;

export default function AIStudioScreen(){
 const [tab,setTab]=useState('coach'); const [coach,setCoach]=useState(null); const [plan,setPlan]=useState(null); const [quiz,setQuiz]=useState(null); const [roadmap,setRoadmap]=useState(null); const [interview,setInterview]=useState(null); const [answer,setAnswer]=useState(''); const [evaluation,setEvaluation]=useState(null); const [search,setSearch]=useState(''); const [results,setResults]=useState([]); const [role,setRole]=useState('AI Engineer'); const [queue,setQueue]=useState(0); const [busy,setBusy]=useState(false);
 const loadCoach=async()=>{setCoach(await api.aiCoach());setQueue(await api.offlineQueueSize())};
 useEffect(()=>{loadCoach().catch(()=>{})},[]);
 const doPlan=async()=>{setBusy(true);try{setPlan(await api.studyPlan({goal:'Become job ready with a personalized learning plan',days:30,minutes_per_day:45}))}catch(e){console.warn('[Student API] Study plan:', e?.message || e)}finally{setBusy(false)}};
 const doQuiz=async()=>{setBusy(true);try{setQuiz(await api.personalizedQuiz({count:5}))}catch(e){console.warn('[Student API] Personalized quiz:', e?.message || e)}finally{setBusy(false)}};
 const doRoadmap=async()=>{setBusy(true);try{setRoadmap(await api.careerRoadmap(role))}catch(e){console.warn('[Student API] Career roadmap:', e?.message || e)}finally{setBusy(false)}};
 const doInterview=async()=>{setBusy(true);try{setInterview(await api.mockInterview({role,difficulty:'intermediate'}));setEvaluation(null);setAnswer('')}catch(e){console.warn('[Student API] Mock interview:', e?.message || e)}finally{setBusy(false)}};
 const doSearch=async()=>{if(search.trim().length<2)return;try{const r=await api.globalSearch(search);setResults(r.results||[]);setTab('search')}catch(e){console.warn('[Student API] Search:', e?.message || e)}};
 const sync=async()=>{const r=await api.syncOffline();setQueue(r.remaining||0)};
 return <AppShell><Header eyebrow="AI Learning Studio" title="Your personal learning command center ✨" subtitle="Coach, study plan, personalized practice, career readiness, interviews and intelligent search in one place." right={<Button title={queue?`☁ ${queue} queued`:'☁ Offline sync'} variant="secondary" onPress={sync}/>}/>
  <Card style={{backgroundColor:colors.navy,borderColor:colors.navy}}><View style={{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:12}}><View style={{flex:1,minWidth:240}}><Badge tone="pink">AI-POWERED LEARNING</Badge><Text style={{fontSize:24,fontWeight:'900',color:'#fff',marginTop:8}}>Learn from your own performance.</Text><Text style={{color:'#CBD5E1',lineHeight:20,marginTop:5}}>The studio turns your progress, quiz results and goals into the next best action.</Text></View><View style={{minWidth:230,flex:1}}><Field value={search} onChangeText={setSearch} placeholder="Search courses, lessons, questions…"/><Button title="🔎 Search everything" onPress={doSearch}/></View></View></Card>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>
   <Tile icon="🤖" title="AI Personal Coach" text="Daily recommendations based on your learning history." onPress={()=>setTab('coach')} tone="purple"/>
   <Tile icon="🧠" title="Personalized Quiz" text="Generate focused practice for your weak areas." onPress={()=>{setTab('quiz');doQuiz()}}/>
   <Tile icon="📅" title="AI Study Plan" text="Build a realistic 30-day plan that adapts to you." onPress={()=>{setTab('plan');doPlan()}}/>
   <Tile icon="🎯" title="Career Roadmap" text="See skills and readiness for your target role." onPress={()=>{setTab('roadmap');doRoadmap()}}/>
   <Tile icon="🎤" title="AI Mock Interview" text="Practice interview questions and get scored feedback." onPress={()=>{setTab('interview');doInterview()}}/>
  </View>
  {tab==='coach'&&<Card><Badge tone="purple">AI Personal Learning Coach</Badge><Text style={{fontSize:20,fontWeight:'900',color:colors.navy,marginTop:8}}>{coach?.coach_message||'Preparing your coach…'}</Text>{coach?.profile&&<View style={{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:14}}>{[['Lessons',coach.profile.completed_lessons],['Tests',coach.profile.attempts],['Average',`${coach.profile.average_score}%`],['Weak topics',coach.profile.weak_topics?.length||0]].map(([a,b])=><View key={a} style={{minWidth:120,flex:1,padding:12,backgroundColor:'#F8FAFC',borderRadius:12}}><Text style={{fontSize:11,color:colors.muted,fontWeight:'800'}}>{a}</Text><Text style={{fontSize:21,fontWeight:'900',color:colors.navy,marginTop:4}}>{b}</Text></View>)}</View>}{coach?.recommendations?.map((x,i)=><View key={i} style={{marginTop:10,padding:13,borderRadius:12,backgroundColor:colors.blueSoft}}><Text style={{fontWeight:'900',color:colors.navy}}>{x.title}</Text><Text style={{fontSize:12,color:colors.muted,marginTop:3}}>{x.description}</Text></View>)}</Card>}
  {tab==='quiz'&&<Card><Badge tone="orange">Adaptive Personalized Quiz</Badge><Text style={{fontSize:20,fontWeight:'900',color:colors.navy,marginTop:8}}>{quiz?.title||'Generating your quiz…'}</Text><Text style={{color:colors.muted,marginTop:4}}>{quiz?.reason}</Text>{quiz?.questions?.map((q,i)=><View key={api.idOf(q)||i} style={{padding:12,backgroundColor:'#F8FAFC',borderRadius:12,marginTop:9}}><Text style={{fontWeight:'900'}}>{i+1}. {q.question||q.text}</Text>{q.options&&<Text style={{color:colors.muted,marginTop:4}}>{q.options.join(' • ')}</Text>}</View>)}<Button title="Generate another quiz" variant="secondary" onPress={doQuiz} style={{marginTop:12}}/></Card>}
  {tab==='plan'&&<Card><Badge tone="blue">AI Study Plan</Badge><Text style={{fontSize:20,fontWeight:'900',color:colors.navy,marginTop:8}}>{plan?.goal||'Creating plan…'}</Text>{plan?.phases?.map((p,i)=><View key={i} style={{marginTop:10,padding:14,borderRadius:14,backgroundColor:'#F8FAFC'}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontWeight:'900'}}>Phase {p.week}: {p.focus}</Text><Badge>{p.days} days</Badge></View>{p.activities?.map((a,j)=><Text key={j} style={{fontSize:12,color:colors.muted,marginTop:5}}>✓ {a}</Text>)}</View>)}<Button title="Regenerate plan" variant="secondary" onPress={doPlan} disabled={busy} style={{marginTop:12}}/></Card>}
  {tab==='roadmap'&&<Card><Badge tone="green">Career Readiness</Badge><Select label="Target role" value={role} onChange={setRole} options={['AI Engineer','Java Developer','Full Stack Developer','Data Scientist'].map(x=>({label:x,value:x}))}/><Button title={busy?'Loading…':'Build roadmap'} onPress={doRoadmap} disabled={busy}/>{roadmap&&<><Text style={{fontSize:26,fontWeight:'900',color:colors.navy,marginTop:15}}>{roadmap.overall_readiness}%</Text><Text style={{fontSize:12,color:colors.muted}}>Overall readiness for {roadmap.role}</Text>{roadmap.skills?.map((s,i)=><View key={s.name} style={{marginTop:12}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontWeight:'800'}}>{s.name}</Text><Text style={{fontWeight:'900'}}>{s.score}%</Text></View><ProgressBar value={s.score} color={s.status==='strong'?colors.success:colors.primary}/></View>)}</>}</Card>}
  {tab==='interview'&&<Card><Badge tone="purple">AI Mock Interview</Badge><Select label="Interview role" value={role} onChange={setRole} options={['AI Engineer','Java Developer','Full Stack Developer'].map(x=>({label:x,value:x}))}/><Button title="Start interview" onPress={doInterview} disabled={busy}/>{interview?.questions?.map((q,i)=><View key={i} style={{marginTop:12,padding:14,backgroundColor:'#F8FAFC',borderRadius:12}}><Text style={{fontWeight:'900'}}>Q{i+1}. {q}</Text>{i===0&&<><Field label="Your answer" value={answer} onChangeText={setAnswer} multiline/><Button title="Evaluate answer" onPress={async()=>{try{setEvaluation(await api.evaluateMockInterview({question:q,answer}))}catch(e){console.warn('[Student API] Evaluation:', e?.message || e)}}}/></>}</View>)}{evaluation&&<Card style={{backgroundColor:colors.purpleSoft,borderColor:'#DDD6FE'}}><Text style={{fontSize:28,fontWeight:'900',color:colors.navy}}>{evaluation.score}/100</Text><Text style={{fontWeight:'900',marginTop:5}}>AI feedback</Text><Text style={{color:colors.muted,lineHeight:19,marginTop:4}}>{evaluation.feedback}</Text></Card>}</Card>}
  {tab==='search'&&<Card><Badge>Global Search</Badge><Text style={{fontSize:19,fontWeight:'900',color:colors.navy,marginTop:8}}>{results.length} results for “{search}”</Text>{results.map((r,i)=><View key={`${r.type}-${r.id}-${i}`} style={{padding:12,backgroundColor:'#F8FAFC',borderRadius:12,marginTop:9}}><View style={{flexDirection:'row',gap:8}}><Badge tone={r.type==='course'?'green':r.type==='lesson'?'blue':'orange'}>{r.type}</Badge><Text style={{fontWeight:'900',flex:1}}>{r.title}</Text></View><Text style={{fontSize:12,color:colors.muted,marginTop:5}}>{r.snippet}</Text></View>)}</Card>}
 </AppShell>
}
