import React,{useEffect,useState} from 'react';
import {Alert,Text,View} from 'react-native';
import {AppShell,Badge,Button,Card,ErrorState,Header,Loading} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';

export default function PersonalizedLearningScreen({openCourse,openAdaptive}){
 const [path,setPath]=useState(null),[adaptive,setAdaptive]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{setError('');setPath(await api.personalizedPath())}catch(e){setError(e?.message||'The personalized learning service is temporarily unavailable.')}};
 useEffect(()=>{load()},[]);
 const startAdaptive=async()=>{setBusy(true);try{setAdaptive(await api.adaptiveTest({count:10}))}catch(e){console.warn('[Student API] Adaptive test:', e?.message || e)}finally{setBusy(false)}};
 if(error)return <AppShell><Header eyebrow="For you" title="Your Learning Plan" subtitle="Personalized recommendations based on your progress."/><ErrorState title="Learning plan is temporarily unavailable" message={error} onRetry={load}/><Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>You can still keep learning</Text><Text style={{color:colors.muted,lineHeight:20,marginTop:5}}>Open My Learning or take a published test while we reconnect the recommendation service.</Text><View style={{flexDirection:'row',gap:8,flexWrap:'wrap',marginTop:14}}>{openAdaptive&&<Button title="Take adaptive test" onPress={openAdaptive}/>}</View></Card></AppShell>;
 if(!path)return <AppShell><Header eyebrow="For you" title="Your Learning Plan" subtitle="Personalized recommendations based on your progress."/><Loading label="Building your learning plan…"/></AppShell>;
 const weak=path.weak_areas||[],next=path.next_steps||[],goal=Number(path.daily_goal_minutes||0);
 return <AppShell><Header eyebrow="For you" title="Your Learning Plan" subtitle="Recommendations are based on your progress and recent assessment performance."/>
  <Card style={{backgroundColor:colors.navy,borderColor:colors.navy}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12}}><View style={{flex:1}}><Text style={{fontSize:20,fontWeight:'900',color:'#fff'}}>Today's goal</Text><Text style={{color:'#E9EAF3',marginTop:4}}>{goal} minutes of focused learning</Text></View><Badge tone="green">Personalized</Badge></View></Card>
  <Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Weak areas</Text>{weak.length?weak.map((x,i)=><View key={i} style={{marginTop:9,padding:11,borderRadius:12,backgroundColor:'#FFF7ED'}}><Text style={{fontWeight:'800',color:colors.navy}}>Quiz {x.quiz_id}</Text><Text style={{fontSize:12,color:colors.muted,marginTop:3}}>Score {x.score}% — review this topic</Text></View>):<Text style={{color:colors.muted,marginTop:8}}>No weak areas detected yet. Keep practicing.</Text>}</Card>
  <Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Recommended next steps</Text>{next.length?next.map((l,i)=><View key={api.idOf(l)||i} style={{marginTop:10,padding:13,borderRadius:12,backgroundColor:'#F8F9FD'}}><Text style={{fontWeight:'900',color:colors.navy}}>{l.title||'Recommended lesson'}</Text><Text style={{color:colors.muted,marginTop:4,lineHeight:18}}>{l.description||'Continue this learning activity.'}</Text>{openCourse&&l.course_id&&<View style={{marginTop:9}}><Button title="Open course" onPress={()=>openCourse(l.course_id)}/></View>}</View>):<Text style={{color:colors.muted,marginTop:8}}>No recommendations yet. Complete a few lessons or tests to personalize this plan.</Text>}</Card>
  <Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Adaptive test</Text><Text style={{color:colors.muted,marginTop:5}}>The difficulty is selected from your recent performance.</Text><View style={{marginTop:12,flexDirection:'row',gap:8,flexWrap:'wrap'}}><Button title={busy?'Preparing...':'Preview adaptive level'} onPress={startAdaptive} disabled={busy}/>{openAdaptive&&<Button title="Take adaptive test" variant="secondary" onPress={openAdaptive}/>}</View>{adaptive&&<View style={{marginTop:14}}><Badge tone="orange">Level: {adaptive.adaptive_level}</Badge><Text style={{fontWeight:'800',marginTop:8}}>Prior average: {adaptive.prior_average}%</Text><Text style={{color:colors.muted,marginTop:6}}>{adaptive.questions?.length||0} questions prepared.</Text></View>}</Card>
 </AppShell>
}
