import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, Text, View, useWindowDimensions } from 'react-native';
import { AppShell, Badge, Button, Card, Empty, ErrorState, Field, Loading, ProgressBar, SectionTitle } from '../../components/UI';
import { api } from '../../services/api';
import { colors } from '../../theme';

const EXAM_CATEGORIES=['SSC','Railway','Banking','UPSC','Computer','Teaching','Defence','State Exams','General','English Spoken','Other'];
const SUBJECTS=['English','Hindi','Math','Reasoning','General Awareness','Current Affairs','Science','Physics','Chemistry','Biology','Computer','Java','Python','PHP','SQL','DBMS','Operating Systems','Networking','Spring Boot','Microservices','Aptitude','Other'];
const catsOf=q=>Array.isArray(q?.categories)&&q.categories.length?q.categories:(q?.category?[q.category]:['General']);
const subjectOf=q=>q?.subject||'General';

function Stat({icon,title,value,delta,tone='blue'}){const bg=tone==='green'?colors.greenSoft:tone==='orange'?colors.orangeSoft:tone==='pink'?colors.pinkSoft:colors.blueSoft;return <Card style={{flex:1,minWidth:155,marginBottom:0,padding:15}}><View style={{flexDirection:'row',alignItems:'center',gap:9}}><View style={{width:38,height:38,borderRadius:12,backgroundColor:bg,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:18}}>{icon}</Text></View><Text style={{fontSize:11,fontWeight:'800',color:colors.muted}}>{title}</Text></View><Text style={{fontSize:24,fontWeight:'900',color:colors.navy,marginTop:10}}>{value}</Text>{delta&&<Text style={{fontSize:10,fontWeight:'800',color:colors.success,marginTop:4}}>{delta}</Text>}</Card>}

function TaxonomyCard({title,count,icon,active,onPress,tone='purple'}){const bg=tone==='green'?colors.greenSoft:tone==='pink'?colors.pinkSoft:tone==='orange'?colors.orangeSoft:colors.purpleSoft;return <Pressable onPress={onPress} style={({pressed})=>({width:150,minWidth:140,opacity:pressed?.82:1})}><Card style={{marginBottom:0,padding:14,borderColor:active?colors.primary:colors.border,backgroundColor:active?colors.blueSoft:'#fff'}}><View style={{width:44,height:44,borderRadius:14,backgroundColor:bg,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:22}}>{icon}</Text></View><Text style={{fontSize:13,fontWeight:'900',color:colors.navy,marginTop:10}} numberOfLines={1}>{title}</Text><Text style={{fontSize:10,color:colors.muted,marginTop:3}}>{count} Quizzes</Text></Card></Pressable>}

function QuizCard({quiz,onOpen,compact=false}){const title=quiz.title||quiz.name||'Practice Quiz';const questions=Number(quiz.question_count||(quiz.question_ids||[]).length||0);const duration=quiz.duration_minutes||20;const completed=quiz.is_completed===true;return <Pressable onPress={()=>onOpen(api.idOf(quiz))} style={({pressed})=>({width:compact?260:290,minWidth:compact?240:270,opacity:pressed?.9:1})}><Card style={{padding:0,overflow:'hidden',marginBottom:0,minHeight:compact?185:220}}><View style={{height:70,backgroundColor:colors.hero,padding:13,justifyContent:'space-between'}}><View style={{flexDirection:'row',gap:6,flexWrap:'wrap'}}>{catsOf(quiz).slice(0,2).map(x=><Badge key={x} tone="purple">{x}</Badge>)}<Badge tone={completed?'green':'orange'}>{completed?'COMPLETED':'READY'}</Badge></View></View><View style={{padding:14,flex:1}}><Text style={{fontSize:16,fontWeight:'900',color:colors.navy}} numberOfLines={2}>{title}</Text><Text style={{fontSize:10,color:colors.muted,marginTop:4}}>{subjectOf(quiz)} · {questions} Questions · {duration} min</Text><View style={{flexDirection:'row',gap:7,flexWrap:'wrap',marginTop:10}}><Badge tone="purple">{subjectOf(quiz)}</Badge>{completed&&<Badge tone="green">Done in any exam category</Badge>}</View><Text style={{fontSize:11,fontWeight:'900',color:colors.primary,marginTop:'auto',paddingTop:12}}>{completed?'Review / Retake →':'Start Quiz →'}</Text></View></Card></Pressable>}

export default function StudentQuizzesScreen({openQuiz}){
 const {width}=useWindowDimensions();const wide=width>=1100;const tablet=width>=720;
 const [items,setItems]=useState([]),[results,setResults]=useState([]),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[subject,setSubject]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{try{setLoading(true);setError('');const [quizData,resultData]=await Promise.all([api.studentQuizzes(),api.allResults()]);setItems(api.listOf(quizData));setResults(api.listOf(resultData));}catch(e){setError(e?.message||'Unable to load quizzes.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const categories=useMemo(()=>{const values=[...EXAM_CATEGORIES,...items.flatMap(catsOf)];return ['All',...Array.from(new Set(values.filter(Boolean)))];},[items]);
 const subjects=useMemo(()=>{const values=[...SUBJECTS,...items.map(subjectOf)];return ['All',...Array.from(new Set(values.filter(Boolean)))];},[items]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(x=>{const cats=catsOf(x);const text=[x.title,x.name,x.description,x.exam,x.subject,...cats].filter(Boolean).join(' ').toLowerCase();return(!q||text.includes(q))&&(!category||category==='All'||cats.includes(category))&&(!subject||subject==='All'||subjectOf(x).toLowerCase()===subject.toLowerCase());});},[items,search,category,subject]);
 const uniqueCompleted=new Set(results.map(r=>r.quiz_group_key||r.test_id||r.quiz_id)).size;const percentages=results.map(r=>Number(r.percentage??r.result?.percentage??0)).filter(Number.isFinite);const average=percentages.length?Math.round(percentages.reduce((a,b)=>a+b,0)/percentages.length):0;const best=percentages.length?Math.max(...percentages):0;
 const categoryCounts=useMemo(()=>categories.slice(1).map(x=>({name:x,count:items.filter(q=>catsOf(q).includes(x)).length})).filter(x=>x.count>0),[categories,items]);
 const subjectCounts=useMemo(()=>subjects.slice(1).map(x=>({name:x,count:items.filter(q=>subjectOf(q).toLowerCase()===x.toLowerCase()).length})).filter(x=>x.count>0),[subjects,items]);
 const continueItems=useMemo(()=>items.filter(x=>!x.is_completed).slice(0,5),[items]);
 if(error)return <AppShell><ErrorState title="Quizzes could not load" message={error} onRetry={load}/></AppShell>;
 if(loading)return <AppShell><Loading label="Preparing your quiz portal…"/></AppShell>;
 return <AppShell>
   <View style={{marginBottom:8}}><Text style={{fontSize:28,fontWeight:'900',color:colors.navy}}>Hello, Student! 👋</Text><Text style={{fontSize:12,color:colors.muted,marginTop:4}}>Choose an exam category or subject and start practicing.</Text></View>
   <Card style={{backgroundColor:'#fff',padding:10,marginBottom:14}}><Field value={search} onChangeText={setSearch} placeholder="Search quizzes, exams, subjects..."/></Card>
   <View style={{flexDirection:'row',flexWrap:'wrap',gap:10,marginBottom:14}}><Stat icon="📝" title="Quizzes Available" value={items.length} delta={`${filtered.length} shown`} tone="blue"/><Stat icon="✓" title="Quizzes Attempted" value={uniqueCompleted} delta={uniqueCompleted?`${results.length} attempts`: 'Start your first quiz'} tone="green"/><Stat icon="🏆" title="Average Score" value={`${average}%`} delta={average?'Keep improving':'No attempts yet'} tone="pink"/><Stat icon="🎯" title="Best Score" value={`${best}%`} delta={best?'Personal best':'Not attempted'} tone="orange"/></View>
   <SectionTitle title="Choose Quiz" subtitle="First choose the exam category, then narrow it down by subject." />
   <View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:8}}>{['All',...categories.filter(x=>x!=='All')].map(x=><Pressable key={x} onPress={()=>setCategory(x==='All'?'':x)} style={{paddingHorizontal:15,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor=((!category&&x==='All')||category===x)?colors.primary:colors.border,backgroundColor=((!category&&x==='All')||category===x)?colors.primary:'#fff'}}><Text style={{fontSize:11,fontWeight:'900',color=((!category&&x==='All')||category===x)?'#fff':colors.text}}>{x}</Text></Pressable>)}</View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:10,paddingVertical:4}}>{categoryCounts.map((x,i)=><TaxonomyCard key={x.name} title={x.name} count={x.count} icon={['🎓','🚆','🏦','🏛️','💻','📚'][i%6]} active={category===x.name} onPress={()=>setCategory(category===x.name?'':x.name)} tone={['green','pink','purple','orange'][i%4]}/>)}</ScrollView>
   <SectionTitle title="Popular Subjects" subtitle="The same subject quiz can belong to multiple exam categories." />
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:10,paddingVertical:4}}>{subjectCounts.slice(0,12).map((x,i)=><TaxonomyCard key={x.name} title={x.name} count={x.count} icon={['⚛️','🧪','➗','🌿','📖','🌐'][i%6]} active={subject===x.name} onPress={()=>setSubject(subject===x.name?'':x.name)} tone={['purple','green','orange','pink'][i%4]}/>)}</ScrollView>
   <SectionTitle title="Continue Learning" subtitle="Unfinished quizzes first." right={<Button title="View all" variant="secondary" onPress={()=>{setCategory('');setSubject('');setSearch('')}}/>}/>
   {continueItems.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12,paddingBottom:4}}>{continueItems.map(q=><QuizCard key={api.idOf(q)} quiz={q} onOpen={openQuiz} compact/>)}</ScrollView>:<Empty title="You completed the available quizzes" message="Explore another subject or exam category for more practice."/>}
   <SectionTitle title={category||subject?`Quizzes in ${category||subject}`:'All Quizzes'} subtitle={`${filtered.length} published quiz${filtered.length===1?'':'zes'} available`} />
   {filtered.length===0?<Empty title="No quizzes found" message="Try another exam category, subject or search term." action={<Button title="Clear filters" variant="secondary" onPress={()=>{setSearch('');setCategory('');setSubject('')}}/>}/>:<View style={{flexDirection:'row',flexWrap:'wrap',gap:14,alignItems:'stretch'}}>{filtered.map(q=><QuizCard key={api.idOf(q)} quiz={q} onOpen={openQuiz}/>)}</View>}
   <Card style={{marginTop:8,backgroundColor:'#EEF0FF',borderColor:'#E2E0FF'}}><Text style={{fontSize:17,fontWeight:'900',color:colors.navy}}>How completion works</Text><Text style={{fontSize:11,color:colors.muted,lineHeight:19,marginTop:5}}>If you complete a quiz under SSC, the matching quiz with the same subject and title under Railway, Banking, UPSC or another exam category is also marked completed.</Text></Card>
 </AppShell>;
}
