import React,{useEffect,useState} from 'react';
import {Alert,Pressable,Text,View} from 'react-native';
import {AppShell,Badge,Button,Card,Empty,ErrorState,Field,Header,Loading,Select} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';

export default function StudentCourseScreen({courseId,onBack,openQuiz}){
 const [data,setData]=useState(null),[progress,setProgress]=useState(null),[completed,setCompleted]=useState([]),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[rating,setRating]=useState(5),[review,setReview]=useState(''),[reviews,setReviews]=useState([]),[bookmarked,setBookmarked]=useState(false);
 const load=async()=>{try{setError('');const [o,p,allProgress,rv,bm]=await Promise.all([api.courseOverview(courseId),api.courseProgress(courseId),api.progress(),api.reviews(courseId),api.bookmarks()]);setData(o);setProgress(p);setCompleted(api.listOf(allProgress).filter(x=>x.course_id===courseId&&x.completed).map(x=>String(x.lesson_id)));setReviews(api.listOf(rv));setBookmarked(api.listOf(bm).some(x=>x.item_type==='course'&&String(x.item_id)===String(courseId)))}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[courseId]);
 if(error)return <AppShell><Header title="Course" right={<Button title="← Back" variant="secondary" onPress={onBack}/>}/><ErrorState title="Course could not load" message={error} onRetry={load}/></AppShell>;
 if(!data)return <AppShell><Loading label="Opening course…"/></AppShell>;
 const c=data.course,mods=data.modules||[],lessons=data.lessons||[],quizzes=data.quizzes||[];
 const complete=async l=>{try{await api.completeLesson(api.idOf(l));const p=await api.courseProgress(courseId);setProgress(p);const all=await api.progress();setCompleted(api.listOf(all).filter(x=>x.course_id===courseId&&x.completed).map(x=>String(x.lesson_id)))}catch(e){Alert.alert('Progress',e.message)}};
 const enroll=async()=>{try{await api.enroll(courseId);Alert.alert('Enrolled','The course is now in My Learning.')}catch(e){Alert.alert('Enrollment',e.message)}};
 const bookmark=async()=>{try{if(bookmarked){Alert.alert('Bookmark','Course is already bookmarked. Open Bookmarks to manage saved items.');return;}await api.addBookmark({item_type:'course',item_id:courseId,title:c.name||c.title});setBookmarked(true)}catch(e){Alert.alert('Bookmark',e.message)}};
 const submitReview=async()=>{try{await api.addReview(courseId,{rating,review});setReview('');const r=await api.reviews(courseId);setReviews(api.listOf(r));Alert.alert('Thank you','Your review has been saved.')}catch(e){Alert.alert('Review',e.message)}};
 const certificate=async()=>{try{const x=await api.issueCertificate(courseId);Alert.alert('Certificate ready',x.certificate_id)}catch(e){Alert.alert('Certificate',e.message)}};
 return <AppShell>
  <Header eyebrow="Course details" title={c.name||c.title} subtitle="Structured lessons, resources, practice and tests" right={<View style={{flexDirection:'row',gap:8}}><Button title={bookmarked?'🔖 Saved':'🔖 Save'} variant="secondary" onPress={bookmark}/><Button title="← Back" variant="secondary" onPress={onBack}/></View>}/>
  <Card style={{backgroundColor:colors.navy,borderColor:colors.navy,padding:24}}><View style={{flexDirection:'row',flexWrap:'wrap',gap:20}}><View style={{flex:1,minWidth:280}}><Badge tone="pink">{c.is_free===false?'PAID':'FREE COURSE'}</Badge><Text style={{fontSize:28,fontWeight:'900',color:'#fff',marginTop:10}}>{c.name||c.title}</Text><Text style={{color:'#CBD5E1',lineHeight:22,marginTop:7}}>{c.description||c.short_description}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12}}><Badge>{c.level||'Beginner'}</Badge><Badge tone="purple">{c.category||'General'}</Badge><Badge tone="green">{c.language||'English'}</Badge><Badge tone="orange">{c.rating||0} ★</Badge></View><Button title="Enroll / Add to My Learning" onPress={enroll} style={{marginTop:15}}/></View><View style={{minWidth:240,backgroundColor:'#fff',borderRadius:16,padding:16}}><Text style={{fontWeight:'900',color:colors.navy}}>Your progress</Text><Text style={{fontSize:30,fontWeight:'900',color:colors.primary,marginTop:5}}>{progress?.percentage||0}%</Text><Text style={{fontSize:12,color:colors.muted}}>{progress?.completed_lessons||0} of {progress?.total_lessons||0} lessons complete</Text><View style={{height:8,borderRadius:10,backgroundColor:'#E5E7EB',marginTop:12,overflow:'hidden'}}><View style={{height:8,width:`${Math.min(100,progress?.percentage||0)}%`,backgroundColor:colors.primary}}/></View></View></View></Card>
  <Card><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{[['overview','Overview'],['curriculum','Curriculum'],['tests','Test Series'],['resources','Resources'],['reviews','Reviews']].map(([x,label])=><Pressable key={x} onPress={()=>setTab(x)} style={{paddingHorizontal:15,paddingVertical:10,borderBottomWidth:2,borderBottomColor:tab===x?colors.primary:'transparent'}}><Text style={{fontWeight:'900',color:tab===x?colors.primary:colors.muted}}>{label}</Text></Pressable>)}</View></Card>
  {tab==='overview'&&<><Card><Text style={{fontSize:19,fontWeight:'900',color:colors.navy}}>About this course</Text><Text style={{color:colors.text,lineHeight:22,marginTop:8}}>{c.description||'Build practical skills through structured topic-wise lessons and assessments.'}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:15}}>{[['👨‍🏫','Instructor',c.instructor_name||'Smart Learning Lab'],['⏱','Duration',`${c.estimated_minutes||0} minutes`],['🎥','Videos',c.video_count||0],['📄','PDFs',c.pdf_count||0],['📝','Mock tests',c.mock_test_count||quizzes.length]].map(([i,a,b])=><View key={a} style={{minWidth:160,padding:12,borderRadius:12,backgroundColor:'#F9FAFB'}}><Text style={{fontSize:20}}>{i}</Text><Text style={{fontSize:12,color:colors.muted,marginTop:5}}>{a}</Text><Text style={{fontWeight:'900',color:colors.navy,marginTop:2}}>{b}</Text></View>)}</View></Card>{Array.isArray(c.learning_objectives)&&c.learning_objectives.length>0&&<Card><Text style={{fontSize:19,fontWeight:'900',color:colors.navy}}>What you'll learn</Text>{c.learning_objectives.map((x,i)=><Text key={i} style={{marginTop:8,color:colors.text}}>✓ {x}</Text>)}</Card>}</>}
  {tab==='curriculum'&&<><Text style={{fontSize:20,fontWeight:'900',color:colors.navy,marginBottom:10}}>Course curriculum</Text>{mods.length===0?<Empty title="Curriculum is not published yet"/>:mods.map((m,mi)=>{const ls=lessons.filter(l=>String(l.topic_id)===String(api.idOf(m)));return <Card key={api.idOf(m)}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{width:38,height:38,borderRadius:12,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'}}><Text style={{fontWeight:'900',color:colors.primary}}>{mi+1}</Text></View><View style={{flex:1}}><Text style={{fontSize:17,fontWeight:'900',color:colors.navy}}>{m.name||m.title}</Text><Text style={{fontSize:12,color:colors.muted}}>{m.description||''}</Text></View></View>{ls.map((l,i)=>{const lid=api.idOf(l);const done=completed.includes(lid);return <View key={lid} style={{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:11,borderTopWidth:1,borderTopColor:colors.border,marginTop:9}}><Text style={{fontSize:18}}>📖</Text><View style={{flex:1}}><Text style={{fontWeight:'800'}}>{i+1}. {l.title||l.name}</Text><Text style={{fontSize:12,color:colors.muted}}>{l.duration_minutes||10} min</Text></View><Button title={done?'Done':'Mark complete'} onPress={()=>complete(l)}/></View>})}</Card>})}</>}
  {tab==='tests'&&<>{quizzes.length===0?<Empty title="No tests published" message="The admin can attach quizzes to this course."/>:quizzes.map(q=><Card key={api.idOf(q)}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{width:42,height:42,borderRadius:12,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'}}><Text>📝</Text></View><View style={{flex:1}}><Text style={{fontSize:17,fontWeight:'900',color:colors.navy}}>{q.title||q.name}</Text><Text style={{color:colors.muted}}>{q.duration_minutes||15} min · {q.question_ids?.length||0} questions · Pass {q.passing_percentage||60}%</Text></View><Button title="Attempt" onPress={()=>openQuiz(api.idOf(q))}/></View></Card>)}</>}
  {tab==='resources'&&<><Card><Text style={{fontSize:19,fontWeight:'900',color:colors.navy}}>Learning resources</Text><Text style={{color:colors.muted,marginTop:5}}>Video lessons, PDFs, notes and practice material can be attached by the admin while creating lessons.</Text></Card>{lessons.flatMap(l=>(l.resources||[]).map((r,i)=><Card key={`${api.idOf(l)}-${i}`}><Text style={{fontWeight:'900',color:colors.navy}}>{l.title||l.name}</Text><Text style={{color:colors.primary,marginTop:5}}>{String(r)}</Text></Card>))}</>}
  {tab==='reviews'&&<><Card><Text style={{fontSize:19,fontWeight:'900',color:colors.navy}}>Rate this course</Text><Select label="Rating" value={rating} onChange={setRating} options={[1,2,3,4,5].map(x=>({label:`${x} ★`,value:x}))}/><Field label="Review" value={review} onChangeText={setReview} placeholder="What did you think about the course?" multiline/><Button title="Submit review" onPress={submitReview}/></Card>{reviews.length===0?<Empty title="No reviews yet" message="Be the first learner to review this course."/>:reviews.map(r=><Card key={api.idOf(r)}><Text style={{fontWeight:'900',color:colors.navy}}>{r.user_name} · {r.rating} ★</Text><Text style={{color:colors.muted,marginTop:5}}>{r.review}</Text></Card>)}</>}
  {(progress?.percentage||0)>=100&&<Card style={{backgroundColor:colors.greenSoft,borderColor:'#86EFAC'}}><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>🎓 Course completed</Text><Text style={{color:colors.muted,marginTop:5}}>You can now request your certificate.</Text><Button title="Get certificate" variant="success" onPress={certificate} style={{marginTop:12}}/></Card>}
 </AppShell>;
}
