import React, {useMemo} from 'react';
import {Pressable, Text, View} from 'react-native';
import {Badge, Button} from './UI';
import {colors} from '../theme';
function unique(v){return Array.from(new Set(v));}
export function TaxonomyPicker({taxonomy=[],categoryIds=[],subcategoryIds=[],onChange,required=true,title='Categories & Subcategories',helper='Select the categories and subcategories that apply to this content.'}){
 const selectedCategories=useMemo(()=>taxonomy.filter(g=>categoryIds.includes(g.id)),[taxonomy,categoryIds]);
 const allSubs=useMemo(()=>taxonomy.flatMap(g=>g.subcategories||[]),[taxonomy]);
 const selectedSubs=useMemo(()=>allSubs.filter(s=>subcategoryIds.includes(s.id)),[allSubs,subcategoryIds]);
 const allCats=taxonomy.length>0&&categoryIds.length===taxonomy.length&&taxonomy.every(g=>categoryIds.includes(g.id));
 const allEverything=allCats&&allSubs.length===selectedSubs.length;
 const allFor=g=>{const ids=(g.subcategories||[]).map(s=>s.id);return ids.length>0&&ids.every(id=>subcategoryIds.includes(id));};
 const toggleCategory=id=>{const next=categoryIds.includes(id)?categoryIds.filter(x=>x!==id):unique([...categoryIds,id]);const allowed=new Set(taxonomy.filter(g=>next.includes(g.id)).flatMap(g=>g.subcategories||[]).map(s=>s.id));onChange({categoryIds:next,subcategoryIds:subcategoryIds.filter(id=>allowed.has(id))});};
 const toggleSub=id=>onChange({categoryIds,subcategoryIds:subcategoryIds.includes(id)?subcategoryIds.filter(x=>x!==id):unique([...subcategoryIds,id])});
 const toggleAllFor=g=>{const ids=(g.subcategories||[]).map(s=>s.id);if(!ids.length)return;onChange({categoryIds,subcategoryIds:allFor(g)?subcategoryIds.filter(id=>!ids.includes(id)):unique([...subcategoryIds,...ids])});};
 const selectAll=()=>onChange({categoryIds:taxonomy.map(g=>g.id),subcategoryIds:allSubs.map(s=>s.id)});
 const clearAll=()=>onChange({categoryIds:[],subcategoryIds:[]});
 const selectAllSelectedCategorySubs=()=>onChange({categoryIds,subcategoryIds:unique([...subcategoryIds,...selectedCategories.flatMap(g=>(g.subcategories||[]).map(s=>s.id))])});
 return <View style={{marginBottom:8}}>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:5}}><Text style={{fontSize:13,fontWeight:'900',color:colors.text}}>{title}{required?' *':''}</Text>{(categoryIds.length||subcategoryIds.length)?<Button title="Clear all" variant="secondary" onPress={clearAll} style={{minHeight:34,paddingHorizontal:11}}/>:null}</View>
  <Text style={{fontSize:12,color:colors.muted,lineHeight:18,marginBottom:10}}>{helper}</Text>
  <View style={{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:8,padding:10,borderRadius:12,backgroundColor:'#F5F7FF',borderWidth:1,borderColor:colors.border,marginBottom:12}}>
   <Text style={{fontSize:11,fontWeight:'900',color:colors.navy}}>Quick selection</Text>
   <Button title={allEverything?'All selected':'Select all'} onPress={selectAll} disabled={allEverything||!taxonomy.length} style={{minHeight:34,paddingHorizontal:11}}/>
   <Button title="Select subcategories" variant="secondary" onPress={selectAllSelectedCategorySubs} disabled={!categoryIds.length} style={{minHeight:34,paddingHorizontal:11}}/>
   <Button title="Clear all" variant="secondary" onPress={clearAll} disabled={!categoryIds.length&&!subcategoryIds.length} style={{minHeight:34,paddingHorizontal:11}}/>
   <Badge tone="pink">{categoryIds.length}/{taxonomy.length} categories</Badge><Badge tone="purple">{selectedSubs.length}/{allSubs.length} subcategories</Badge>
  </View>
  <Text style={{fontSize:12,fontWeight:'900',color:colors.navy,marginBottom:8}}>1. Categories</Text>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{taxonomy.map(g=>{const selected=categoryIds.includes(g.id);const count=(g.subcategories||[]).filter(s=>subcategoryIds.includes(s.id)).length;const total=(g.subcategories||[]).length;return <Pressable key={g.id} onPress={()=>toggleCategory(g.id)} style={{minWidth:175,borderWidth:1,borderColor:selected?'#B9B1FF':colors.border,borderRadius:12,paddingHorizontal:12,paddingVertical:10,backgroundColor:selected?colors.blueSoft:'#fff'}}><View style={{flexDirection:'row',alignItems:'center',gap:7}}><Text style={{fontSize:16,color:selected?colors.primary:colors.subtle}}>{selected?'☑':'☐'}</Text><Text style={{flex:1,fontWeight:'900',fontSize:12,color:selected?colors.primary:colors.text}}>{g.name}</Text></View><Text style={{fontSize:10,color:colors.muted,marginTop:4,marginLeft:24}}>{count}/{total} subcategories selected</Text></Pressable>})}</View>
  {selectedCategories.length?<View style={{marginTop:15,borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:'#FAFCFF',padding:12}}><Text style={{fontSize:12,fontWeight:'900',color:colors.navy,marginBottom:3}}>2. Subcategories</Text><Text style={{fontSize:11,color:colors.muted,marginBottom:10}}>Select individual items, or use “Select all” for a category. You can deselect any item later.</Text>{selectedCategories.map(g=><View key={g.id} style={{marginBottom:14}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:7}}><View style={{flexDirection:'row',alignItems:'center',gap:7}}><Text style={{fontSize:12,fontWeight:'900',color:colors.text}}>{g.name}</Text><Badge tone="blue">{(g.subcategories||[]).filter(s=>subcategoryIds.includes(s.id)).length}/{(g.subcategories||[]).length}</Badge></View>{g.subcategories?.length?<Pressable onPress={()=>toggleAllFor(g)}><Text style={{fontSize:11,fontWeight:'900',color:colors.primary}}>{allFor(g)?'Clear all':'Select all'}</Text></Pressable>:null}</View><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{(g.subcategories||[]).map(sub=>{const selected=subcategoryIds.includes(sub.id);return <Pressable key={sub.id} onPress={()=>toggleSub(sub.id)} style={{minWidth:165,flexGrow:1,borderWidth:1,borderColor:selected?'#B9B1FF':colors.border,borderRadius:10,paddingHorizontal:10,paddingVertical:9,backgroundColor:selected?colors.purpleSoft:'#fff',flexDirection:'row',alignItems:'center',gap:8}}><Text style={{fontSize:15,color:selected?colors.purple:colors.subtle}}>{selected?'☑':'☐'}</Text><Text style={{flex:1,fontSize:11,fontWeight:selected?'900':'700',color:selected?colors.purple:colors.text}}>{sub.name}</Text></Pressable>})}</View></View>)}</View>:<View style={{marginTop:12,borderWidth:1,borderStyle:'dashed',borderColor:colors.border,borderRadius:12,padding:12,backgroundColor:'#FAFAFC'}}><Text style={{fontSize:12,color:colors.muted}}>Select at least one category to see its subcategories.</Text></View>}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:9}}>{categoryIds.length?<Badge tone="pink">{categoryIds.length} categor{categoryIds.length===1?'y':'ies'}</Badge>:null}{subcategoryIds.length?<Badge tone="purple">{subcategoryIds.length} subcategor{subcategoryIds.length===1?'y':'ies'}</Badge>:null}</View>
 </View>;
}
