import React from 'react';import{View,Text,Pressable,StyleSheet,ScrollView}from'react-native';import{enterpriseTheme as t}from'./theme';
const Metric=({value,label,caption})=><View style={s.metric}><Text style={s.mv}>{value}</Text><Text style={s.ml}>{label}</Text><Text style={s.cap}>{caption}</Text></View>;
const Progress=({value})=><View style={s.track}><View style={[s.fill,{width:`${Math.max(0,Math.min(100,value))}%`}]}/></View>;
export default function EnterpriseStudentHome({name='Learner',onContinue,onAI,onInterview,onQuiz}){return <ScrollView contentContainerStyle={s.c}>
<View style={s.hero}><Text style={s.badge}>AI LEARNING</Text><Text style={s.greet}>Good morning, {name} 👋</Text><Text style={s.sub}>Your personalized learning command center.</Text><View style={s.streak}><Text style={s.fire}>🔥</Text><View><Text style={s.st}>12 day streak</Text><Text style={s.ss}>Keep your momentum today</Text></View></View></View>
<View style={s.row}><Metric value="78%" label="Progress" caption="+6% this week"/><Metric value="82%" label="Avg. score" caption="Above target"/><Metric value="24h" label="Learning" caption="This month"/></View>
<View style={s.card}><Text style={s.ey}>TODAY'S LEARNING</Text><Text style={s.title}>Java Collections</Text><Text style={s.body}>25 minutes · Continue from your last lesson</Text><Progress value={68}/><Text style={s.cap}>68% complete</Text><Pressable style={s.primary} onPress={onContinue}><Text style={s.pt}>Continue learning →</Text></Pressable></View>
<View style={s.card}><Text style={s.ey}>YOUR AI COACH</Text><Text style={s.title}>“Revise HashMap today.”</Text><Text style={s.body}>Your recent quizzes show HashMap collision handling is a weak area.</Text><Pressable style={s.secondary} onPress={onAI}><Text style={s.st}>Open AI Coach</Text></Pressable></View>
<Text style={s.section}>Career readiness</Text><View style={s.card}><View style={s.between}><Text style={s.title}>Java Developer</Text><Text style={s.score}>72%</Text></View><Progress value={72}/><Text style={s.body}>Next best skill: Kafka</Text></View>
<Text style={s.section}>Recommended for you</Text><View style={s.row}><Pressable style={s.action} onPress={onQuiz}><Text style={s.icon}>🤖</Text><Text style={s.at}>5 AI questions</Text><Text style={s.as}>Weak topics</Text></Pressable><Pressable style={s.action} onPress={onInterview}><Text style={s.icon}>🎤</Text><Text style={s.at}>Mock interview</Text><Text style={s.as}>Java Developer</Text></Pressable></View>
</ScrollView>}
const s=StyleSheet.create({c:{padding:20,paddingBottom:40,backgroundColor:t.colors.background},hero:{backgroundColor:t.colors.primary,borderRadius:28,padding:24,marginBottom:16},badge:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},greet:{color:'#fff',fontSize:27,fontWeight:'900',marginTop:12},sub:{color:'rgba(255,255,255,.8)',marginTop:5},streak:{flexDirection:'row',alignItems:'center',marginTop:18,backgroundColor:'rgba(255,255,255,.12)',borderRadius:16,padding:12},fire:{fontSize:25,marginRight:10},st:{fontWeight:'800',color:'#fff'},ss:{fontSize:11,color:'rgba(255,255,255,.7)',marginTop:2},row:{flexDirection:'row',gap:10},metric:{flex:1,backgroundColor:'#fff',borderRadius:18,padding:13,borderWidth:1,borderColor:t.colors.border},mv:{fontSize:21,fontWeight:'900',color:t.colors.text},ml:{fontSize:11,fontWeight:'800',marginTop:3,color:t.colors.text},cap:{fontSize:10,color:t.colors.muted,marginTop:4},card:{backgroundColor:'#fff',borderRadius:20,padding:18,marginTop:16,borderWidth:1,borderColor:t.colors.border},ey:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:t.colors.primary},title:{fontSize:18,fontWeight:'900',color:t.colors.text,marginTop:6},body:{fontSize:13,color:t.colors.muted,lineHeight:19,marginTop:5},track:{height:8,backgroundColor:'#E5E7EB',borderRadius:8,overflow:'hidden',marginTop:14},fill:{height:'100%',backgroundColor:t.colors.primary},primary:{marginTop:14,backgroundColor:t.colors.primary,borderRadius:14,padding:14,alignItems:'center'},pt:{color:'#fff',fontWeight:'900'},secondary:{marginTop:14,borderWidth:1,borderColor:t.colors.primary,borderRadius:14,padding:13,alignItems:'center'},section:{fontSize:18,fontWeight:'900',marginTop:22,color:t.colors.text},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},score:{fontSize:22,fontWeight:'900',color:t.colors.primary},action:{flex:1,backgroundColor:'#fff',borderRadius:18,padding:16,borderWidth:1,borderColor:t.colors.border},icon:{fontSize:23},at:{fontSize:14,fontWeight:'900',marginTop:9,color:t.colors.text},as:{fontSize:11,color:t.colors.muted,marginTop:3}});