import React, {useEffect, useMemo, useState} from 'react';
import {Alert, Text, View} from 'react-native';
import {AppShell, Badge, Button, Card, DropdownSelect, Empty, ErrorState, Field, Header, Loading} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';
import {TaxonomyPicker} from '../../components/TaxonomyPicker';

const LEVELS=['All','Beginner','Intermediate','Advanced'];
const LANGUAGES=['All','English','Hindi','Hinglish'];
const STATUS=['All','Published','Unpublished'];
const DEFAULT_FORM={name:'',short_description:'',description:'',subject:'English',category_ids:[],categories:[],subcategory_ids:[],subcategories:[],exam:'',language:'English',level:'Beginner',instructor_name:'Smart Learning Lab',estimated_minutes:'0',tags:''};

function namesForIds(groups,ids,key){const set=new Set(ids||[]);return groups.flatMap(g=>key==='category'? (set.has(g.id)?[g.name]:[]) : (g.subcategories||[]).filter(s=>set.has(s.id)).map(s=>s.name));}

export default function AdminCoursesScreen({openCourse}){
  const [courses,setCourses]=useState(null),[taxonomy,setTaxonomy]=useState([]),[error,setError]=useState(''),[show,setShow]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(DEFAULT_FORM);
  const [search,setSearch]=useState(''),[category,setCategory]=useState('All'),[subcategory,setSubcategory]=useState('All'),[subject,setSubject]=useState('All'),[status,setStatus]=useState('All'),[level,setLevel]=useState('All'),[language,setLanguage]=useState('All'),[busyId,setBusyId]=useState('');
  const load=async()=>{setError('');try{const [c,t]=await Promise.all([api.courses(),api.adminTaxonomy()]);setCourses(api.listOf(c));setTaxonomy(t?.categories||[]);}catch(e){setError(e?.message||'Unable to load courses.')}};
  useEffect(()=>{load()},[]);
  const reset=()=>{setForm({...DEFAULT_FORM,category_ids:[],categories:[],subcategory_ids:[],subcategories:[]});setEditing(null);setShow(false)};
  const clearFilters=()=>{setSearch('');setCategory('All');setSubcategory('All');setSubject('All');setStatus('All');setLevel('All');setLanguage('All')};
  const allSubcategories=useMemo(()=>taxonomy.flatMap(g=>g.subcategories||[]),[taxonomy]);
  const filterSubcats=useMemo(()=>category==='All'?allSubcategories:(taxonomy.find(g=>g.name===category)?.subcategories||[]),[taxonomy,category,allSubcategories]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return (courses||[]).filter(c=>{const cats=Array.isArray(c.categories)?c.categories:(c.category?[c.category]:[]);const subs=Array.isArray(c.subcategories)?c.subcategories:(c.subcategory?[c.subcategory]:[]);const text=[c.name,c.title,c.short_description,c.description,c.subject,c.exam,c.language,c.level,...cats,...subs,...(Array.isArray(c.tags)?c.tags:[])].filter(Boolean).join(' ').toLowerCase();return (!q||text.includes(q))&&(category==='All'||cats.some(x=>x.toLowerCase()===category.toLowerCase()))&&(subcategory==='All'||subs.some(x=>x.toLowerCase()===subcategory.toLowerCase()))&&(subject==='All'||String(c.subject||'Other')===subject)&&(status==='All'||(status==='Published'?c.is_published===true:c.is_published!==true))&&(level==='All'||String(c.level||'Beginner')===level)&&(language==='All'||String(c.language||'English')===language)})},[courses,search,category,subcategory,subject,status,level,language]);
  const save=async()=>{try{if(!form.name.trim())throw new Error('Course name is required.');if(!form.subject.trim())throw new Error('Subject is required.');if(!form.category_ids.length)throw new Error('Select at least one category.');if(!form.subcategory_ids.length)throw new Error('Select at least one subcategory from the selected categories.');const categories=namesForIds(taxonomy,form.category_ids,'category'),subcategories=namesForIds(taxonomy,form.subcategory_ids,'subcategory');const body={...form,subject:form.subject.trim(),category_ids:form.category_ids,categories,subcategory_ids:form.subcategory_ids,subcategories,category:categories[0],subcategory:subcategories[0],estimated_minutes:Number(form.estimated_minutes)||0,tags:typeof form.tags==='string'?form.tags.split(',').map(x=>x.trim()).filter(Boolean):form.tags,is_free:true,is_published:editing?Boolean(form.is_published):false};if(editing)await api.updateCourse(editing,body);else await api.createCourse(body);reset();await load()}catch(e){Alert.alert('Save failed',e.message)}};
  const edit=c=>{setEditing(api.idOf(c));const catIds=Array.isArray(c.category_ids)&&c.category_ids.length?c.category_ids:taxonomy.filter(g=>(c.categories||[c.category]).some(n=>n&&n.toLowerCase()===g.name.toLowerCase())).map(g=>g.id);const subIds=Array.isArray(c.subcategory_ids)?c.subcategory_ids:taxonomy.flatMap(g=>g.subcategories||[]).filter(s=>(c.subcategories||[c.subcategory]).some(n=>n&&n.toLowerCase()===s.name.toLowerCase())).map(s=>s.id);setForm({...DEFAULT_FORM,...c,subject:c.subject||'Other',category_ids:catIds,categories:c.categories||[],subcategory_ids:subIds,subcategories:c.subcategories||[],estimated_minutes:String(c.estimated_minutes||0),tags:Array.isArray(c.tags)?c.tags.join(', '):(c.tags||'')});setShow(true)};
  const remove=async c=>{try{await api.deleteCourse(api.idOf(c));await load()}catch(e){Alert.alert('Delete failed',e.message)}};
  const togglePublish=async c=>{const id=api.idOf(c);setBusyId(id);try{if(c.is_published)await api.unpublishCourse(id);else await api.publishCourse(id);await load()}catch(e){Alert.alert('Course status',e.message)}finally{setBusyId('')}};
  if(error)return <AppShell><Header title="Courses"/><ErrorState title="Courses could not load" message={error} onRetry={load}/></AppShell>;
  if(!courses)return <AppShell><Loading label="Loading courses..."/></AppShell>;
  return <AppShell>
    <Header eyebrow="Content studio" title="Courses" subtitle="Manage course subject, linked exam categories and category-specific subcategories." right={<Button title={show?'Close':'+ New Course'} onPress={()=>show?reset():setShow(true)}/>}/>
    {show&&<Card><Text style={{fontSize:20,fontWeight:'900',color:colors.navy,marginBottom:14}}>{editing?'Edit course':'Create a new course'}</Text><Field label="Course name *" value={form.name} onChangeText={v=>setForm({...form,name:v})} placeholder="English Grammar - Complete Course"/><Field label="Subject *" value={form.subject} onChangeText={v=>setForm({...form,subject:v})} placeholder="English, Java, Math..."/>
      <TaxonomyPicker
        taxonomy={taxonomy}
        categoryIds={form.category_ids}
        subcategoryIds={form.subcategory_ids}
        onChange={({categoryIds, subcategoryIds}) => setForm({...form, category_ids:categoryIds, categories:namesForIds(taxonomy,categoryIds,'category'), subcategory_ids:subcategoryIds, subcategories:namesForIds(taxonomy,subcategoryIds,'subcategory')})}
        helper="Select multiple categories. Once a category is selected, only its subcategories are shown below."
      />
      <View style={{flexDirection:'row',gap:10,flexWrap:'wrap'}}><View style={{flex:1,minWidth:230}}><Field label="Exam / Target (optional)" value={form.exam} onChangeText={v=>setForm({...form,exam:v})} placeholder="SSC CGL 2026"/></View><View style={{flex:1,minWidth:230}}><Field label="Short description" value={form.short_description} onChangeText={v=>setForm({...form,short_description:v})}/></View></View><Field label="Full description" value={form.description} onChangeText={v=>setForm({...form,description:v})} multiline/>
      <View style={{flexDirection:'row',gap:10,flexWrap:'wrap'}}><View style={{flex:1,minWidth:180}}><DropdownSelect label="Level" value={form.level} onChange={v=>setForm({...form,level:v})} options={LEVELS.filter(x=>x!=='All').map(x=>({value:x,label:x}))}/></View><View style={{flex:1,minWidth:180}}><DropdownSelect label="Language" value={form.language} onChange={v=>setForm({...form,language:v})} options={LANGUAGES.filter(x=>x!=='All').map(x=>({value:x,label:x}))}/></View><View style={{flex:1,minWidth:180}}><Field label="Duration (min)" value={form.estimated_minutes} onChangeText={v=>setForm({...form,estimated_minutes:v})} keyboardType="numeric"/></View></View>
      <View style={{flexDirection:'row',gap:8}}><Button title={editing?'Save Changes':'Create Course'} onPress={save} disabled={!form.name.trim()||!form.subject.trim()||!form.category_ids.length||!form.subcategory_ids.length}/><Button title="Cancel" variant="secondary" onPress={reset}/></View>
    </Card>}
    <Card style={{backgroundColor:'#FBFBFE'}}><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Find a course</Text><Text style={{fontSize:12,color:colors.muted,marginBottom:12}}>Filter by category, category-specific subcategory, subject, publish state, level and language.</Text><Field label="Search" value={search} onChangeText={setSearch} placeholder="Search course, subject, category, subcategory..."/><View style={{flexDirection:'row',gap:10,flexWrap:'wrap'}}><View style={{flex:1,minWidth:180}}><DropdownSelect label="Category" value={category} onChange={v=>{setCategory(v);setSubcategory('All')}} options={[{value:'All',label:'All'},...taxonomy.map(x=>({value:x.name,label:x.name}))]}/></View><View style={{flex:1,minWidth:180}}><DropdownSelect label="Subcategory" value={subcategory} onChange={setSubcategory} options={[{value:'All',label:'All'},...filterSubcats.map(x=>({value:x.name,label:x.name}))]}/></View><View style={{flex:1,minWidth:180}}><DropdownSelect label="Subject" value={subject} onChange={setSubject} options={[{value:'All',label:'All'},...Array.from(new Set((courses||[]).map(x=>x.subject).filter(Boolean))).sort().map(x=>({value:x,label:x}))]}/></View><View style={{flex:1,minWidth:180}}><DropdownSelect label="Publish status" value={status} onChange={setStatus} options={STATUS.map(x=>({value:x,label:x}))}/></View><View style={{flex:1,minWidth:180}}><DropdownSelect label="Level" value={level} onChange={setLevel} options={LEVELS.map(x=>({value:x,label:x}))}/></View><View style={{flex:1,minWidth:180}}><DropdownSelect label="Language" value={language} onChange={setLanguage} options={LANGUAGES.map(x=>({value:x,label:x}))}/></View></View><View style={{flexDirection:'row',gap:8}}><Button title="Reset filters" variant="secondary" onPress={clearFilters}/><Button title="↻ Refresh" variant="secondary" onPress={load}/></View></Card>
    <View style={{flexDirection:'row',gap:8,marginBottom:10,flexWrap:'wrap'}}><Badge tone="pink">COURSE CATALOG</Badge><Badge>{filtered.length} of {courses.length} courses</Badge><Badge tone="green">{courses.filter(c=>c.is_published).length} Published</Badge><Badge tone="orange">{courses.filter(c=>!c.is_published).length} Unpublished</Badge></View>
    {filtered.length===0?<Empty title="No matching courses" message="Try another search or reset the filters."/>:filtered.map(c=>{const cats=c.categories||[];const subs=c.subcategories||[];return <Card key={api.idOf(c)}><View style={{flexDirection:'row',gap:15,alignItems:'center'}}><View style={{width:58,height:58,borderRadius:14,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:27}}>📚</Text></View><View style={{flex:1}}><Text style={{fontSize:19,fontWeight:'900',color:colors.navy}}>{c.name||c.title}</Text><Text style={{color:colors.muted,marginTop:4}} numberOfLines={2}>{c.short_description||c.description||'No description added yet.'}</Text><View style={{flexDirection:'row',gap:7,marginTop:9,flexWrap:'wrap'}}><Badge tone="purple">Subject: {c.subject||'Other'}</Badge>{cats.map(x=><Badge key={x} tone="pink">{x}</Badge>)}{subs.slice(0,8).map(x=><Badge key={x} tone="blue">{x}</Badge>)}<Badge tone={c.is_published?'green':'orange'}>{c.is_published?'Published':'Unpublished'}</Badge></View></View></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14}}><Button title="Manage Course →" onPress={()=>openCourse(api.idOf(c))}/><Button title="Edit" variant="secondary" onPress={()=>edit(c)}/><Button title={busyId===api.idOf(c)?'Updating...':c.is_published?'Unpublish':'Publish'} variant={c.is_published?'secondary':'success'} onPress={()=>togglePublish(c)} disabled={busyId===api.idOf(c)}/><Button title="Delete" variant="danger" onPress={()=>remove(c)}/></View></Card>})}
  </AppShell>;
}
