import React,{useEffect,useState} from 'react';
import {Alert,Text,View} from 'react-native';
import {AppShell,Badge,Button,Card,Empty,ErrorState,Field,Header,Loading,Select} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';

const blank={question:'',options:['','','',''],correct_answer:0,difficulty:'easy',explanation:'',marks:1,negative_marks:0,is_published:true};
export default function AdminQuestionsScreen(){
 const [items,setItems]=useState(null),[error,setError]=useState(''),[show,setShow]=useState(false),[form,setForm]=useState(blank),[search,setSearch]=useState(''),[filter,setFilter]=useState('');
 const load=()=>{setError('');api.questions({search,difficulty:filter}).then(x=>setItems(api.listOf(x))).catch(e=>setError(e.message))};
 useEffect(()=>{load()},[filter]);
 const save=async()=>{try{const payload={...form,answer:form.correct_answer,question_type:'mcq'};await api.createQuestion(payload);setForm(blank);setShow(false);load()}catch(e){Alert.alert('Question error',e.message)}};
 const remove=async id=>{try{await api.deleteQuestion(id);load()}catch(e){Alert.alert('Delete failed',e.message)}};
 if(error)return <AppShell><Header title="Question Bank" subtitle="Create reusable MCQs with difficulty, answers and explanations."/><ErrorState title="Question bank could not load" message={error} onRetry={load}/></AppShell>;
 return <AppShell><Header title="Question Bank" subtitle="Create reusable MCQs with difficulty, answers and explanations." right={<Button title={show?'Close':'+ New Question'} onPress={()=>setShow(!show)}/>}/><Card><View style={{flexDirection:'row',gap:8}}><View style={{flex:1}}><Field label="Search" value={search} onChangeText={setSearch} placeholder="Search questions..."/></View><Button title="Search" variant="secondary" onPress={load}/></View><Select label="Difficulty" value={filter} onChange={setFilter} options={[{value:'',label:'All'},{value:'easy',label:'Easy'},{value:'medium',label:'Medium'},{value:'hard',label:'Hard'}]}/></Card>{show&&<Card><Text style={{fontSize:20,fontWeight:'900',marginBottom:14}}>Create question</Text><Field label="Question" value={form.question} onChangeText={v=>setForm({...form,question:v})} multiline placeholder="Which sentence is correct?"/>{form.options.map((v,i)=><Field key={i} label={`Option ${String.fromCharCode(65+i)}`} value={v} onChangeText={x=>{const a=[...form.options];a[i]=x;setForm({...form,options:a})}} placeholder={`Option ${String.fromCharCode(65+i)}`}/>)}<Select label="Correct answer" value={form.correct_answer} onChange={v=>setForm({...form,correct_answer:v})} options={form.options.map((_,i)=>({value:i,label:`Option ${String.fromCharCode(65+i)}`}))}/><Select label="Difficulty" value={form.difficulty} onChange={v=>setForm({...form,difficulty:v})} options={[{value:'easy',label:'Easy'},{value:'medium',label:'Medium'},{value:'hard',label:'Hard'}]}/><Field label="Explanation" value={form.explanation} onChangeText={v=>setForm({...form,explanation:v})} multiline placeholder="Explain why the answer is correct."/><View style={{flexDirection:'row',gap:8}}><Button title="Save Question" onPress={save} disabled={!form.question.trim()||form.options.some(x=>!x.trim())}/><Button title="Cancel" variant="secondary" onPress={()=>setShow(false)}/></View></Card>}{!items?<Loading/>:items.length===0?<Empty title="No questions found" message="Create your first question or change your filters."/>:items.map(q=><Card key={api.idOf(q)}><View style={{flexDirection:'row',gap:12}}><View style={{flex:1}}><Text style={{fontSize:16,fontWeight:'900',color:colors.navy}}>{q.question}</Text><View style={{flexDirection:'row',gap:7,marginTop:8}}><Badge tone={q.difficulty==='hard'?'purple':q.difficulty==='medium'?'orange':'green'}>{String(q.difficulty||'easy').toUpperCase()}</Badge><Badge>{q.question_type||'MCQ'}</Badge></View><Text style={{color:colors.muted,marginTop:8}}>{Array.isArray(q.options)?q.options.map((o,i)=>`${String.fromCharCode(65+i)}. ${o}`).join('  '):''}</Text><Text style={{color:colors.success,fontWeight:'800',marginTop:7}}>Correct: {q.correct_answer ?? q.answer ?? '-'}</Text></View><Button title="Delete" variant="danger" onPress={()=>remove(api.idOf(q))}/></View></Card>)}</AppShell>;
}
