import React,{useEffect,useState} from 'react';
import {Alert,Text,View} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {AppShell,Badge,Button,Card,Field,Header,ProgressBar} from '../../components/UI';
import {api} from '../../services/api';
import {colors} from '../../theme';

export default function AdminIntelligenceScreen({navigate}){
 const [risk,setRisk]=useState(null),[pdf,setPdf]=useState(null),[busy,setBusy]=useState(false),[courseId,setCourseId]=useState(''),[health,setHealth]=useState(null);
 const load=async()=>{try{setRisk(await api.atRiskStudents())}catch(e){setRisk({error:e.message})}};
 useEffect(()=>{load()},[]);
 const pickPdf=async()=>{try{const r=await DocumentPicker.getDocumentAsync({type:'application/pdf',copyToCacheDirectory:true});if(r.canceled)return;setBusy(true);const f=r.assets[0];const generated=await api.uploadPdfCourse({uri:f.uri,name:f.name,type:'application/pdf'});setPdf(generated)}catch(e){Alert.alert('PDF course generator',e.message)}finally{setBusy(false)}};
 const savePdf=async()=>{if(!pdf)return;try{const r=await api.savePdfCourse(pdf);Alert.alert('Draft saved',`${r.title||'Course'} is now available in Course Builder.`);navigate?.('courses')}catch(e){Alert.alert('Save draft',e.message)}};
 const checkHealth=async()=>{try{setHealth(await api.courseHealth(courseId.trim()))}catch(e){Alert.alert('Course health',e.message)}};
 return <AppShell><Header eyebrow="Admin Intelligence" title="Operate your learning platform with AI" subtitle="Detect struggling students, generate complete courses from PDFs and monitor course health."/>
 <View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}><Card style={{flex:1,minWidth:260,backgroundColor:colors.navy,borderColor:colors.navy}}><Text style={{fontSize:24,fontWeight:'900',color:'#fff'}}>🚨 At-risk students</Text><Text style={{color:'#CBD5E1',marginTop:5}}>Automatically identify low scores, inactivity and stalled enrollments.</Text><Text style={{fontSize:34,fontWeight:'900',color:'#fff',marginTop:15}}>{risk?.summary?.high||0}</Text><Text style={{color:'#CBD5E1'}}>high risk</Text><Text style={{fontSize:13,color:'#CBD5E1',marginTop:3}}>{risk?.summary?.medium||0} medium risk</Text></Card><Card style={{flex:1,minWidth:260}}><Badge tone="purple">PDF → AI COURSE</Badge><Text style={{fontSize:20,fontWeight:'900',color:colors.navy,marginTop:8}}>Turn learning material into a draft course</Text><Text style={{color:colors.muted,lineHeight:19,marginTop:5}}>Upload a text-based PDF. The platform extracts modules, lessons, summaries and learning objectives.</Text><Button title={busy?'Generating…':'📄 Choose PDF & Generate'} onPress={pickPdf} disabled={busy} style={{marginTop:12}}/></Card></View>
 {risk?.students?.length>0&&<Card><Text style={{fontSize:19,fontWeight:'900',color:colors.navy}}>Students needing attention</Text>{risk.students.slice(0,12).map((s,i)=><View key={s.student_id||i} style={{padding:12,backgroundColor:'#F8FAFC',borderRadius:12,marginTop:8}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontWeight:'900'}}>{s.name}</Text><Badge tone={s.risk==='high'?'red':'orange'}>{s.risk.toUpperCase()}</Badge></View><Text style={{fontSize:12,color:colors.muted,marginTop:4}}>Score: {s.average_score}% · {s.reasons?.join(' · ')}</Text></View>)}</Card>}
 {pdf&&<Card><Badge tone="purple">Generated Course Preview</Badge><Text style={{fontSize:22,fontWeight:'900',color:colors.navy,marginTop:8}}>{pdf.title}</Text><Text style={{color:colors.muted,marginTop:4}}>{pdf.modules?.length||0} modules · {pdf.question_count||0} suggested questions</Text>{pdf.modules?.map((m,i)=><View key={i} style={{padding:12,backgroundColor:'#F8FAFC',borderRadius:12,marginTop:8}}><Text style={{fontWeight:'900'}}>{i+1}. {m.title}</Text><Text style={{fontSize:12,color:colors.muted,marginTop:3}}>{m.lessons?.length||0} lessons</Text></View>)}<Button title="Save as draft course" onPress={savePdf} style={{marginTop:12}}/></Card>}
 <Card><Badge>AI Course Health Checker</Badge><Text style={{fontSize:19,fontWeight:'900',color:colors.navy,marginTop:8}}>Check any course for content and engagement risks.</Text><Field label="Course ID" value={courseId} onChangeText={setCourseId} placeholder="Paste course ID"/><Button title="Analyze course" onPress={checkHealth}/>{health&&<><Text style={{fontSize:34,fontWeight:'900',color:colors.navy,marginTop:15}}>{health.health_score}/100</Text><ProgressBar value={health.health_score}/>{Object.entries(health.metrics||{}).map(([k,v])=><View key={k} style={{marginTop:10,flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:colors.muted}}>{k.replaceAll('_',' ')}</Text><Text style={{fontWeight:'900'}}>{v}</Text></View>)}{health.issues?.map((x,i)=><Text key={i} style={{color:colors.danger,marginTop:8}}>⚠ {x}</Text>)}</>}</Card>
 </AppShell>
}
